---
- name: Create Dir to Downlaod Tomcat. 
  file: path=/etc/artifact state=directory

- maven_artifact:
    group_id: com.mindtree
    artifact_id: devops
    extension: war
    repository_url: 'http://kkscj76483dns.eastus2.cloudapp.azure.com:8082/artifactory/webapp/#/artifacts/browse/tree/General/devops'
    dest: /etc/artifact/devops.war
